debug-mode: true
data-type: SQLite # You can choose JSON, SQLite, or MySQL
connection-params:
  address: "localhost:3306"
  username: "user"
  password: "myPassword"
  database: "ChatMacro"
macro-limits:
  enabled: true
  groups: # Give the chatmacro.limit.none permission for unlimited macros
    default: 1 # Default limit if they don't have chatmacro.limit.<group>
    vip: 2 # chatmacro.limit.vip
    mvp: 3 # chatmacro.limit.mvp
