debug-mode: false
data-type: SQLite # You can choose JSON, SQLite, or MySQL for this
connection-params:
  file: "data.db" # If you choose MySQL for this option you will need to supply the username, password, database, and port